### ISSUE TITLE
International keys & Launguage keys not working on macOS

### ISSUE THREAD

**Issue by jdack41** [zmkfirmware/zmk#1236]
INT_RO, INT_YEN, LANG1, LANG2 not working on macOS, but worked on Windows(both of them set on Japanese environment).
These keys used on JIS layout mac keyboards.

**Comment by yemartin** [comment]
With a Kinesis Advantage360 Pro, even with the fix introduced by #1521, `LANG1` and `LANG2` did not work out of the box on macOS. `Key Codes.app` would not show any output when pressing these keys.

The Kinesis firmware builder tool has [NKRO enabled by default](https://github.com/KinesisCorporation/Adv360-Pro-ZMK/blob/09ff934f7d2a42e3b0b8e3f65595732536baf72d/config/boards/arm/adv360/adv360_left_defconfig#L53). But I had to [turn NKRO off](https://github.com/yemartin/Adv360-Pro-ZMK/commit/05840e690a687ea27ff743488837c48d50b59978) to get `LANG1` and `LANG2` to work (thanks to @caksoylar invaluable help and [spot-on suggestion](https://discord.com/channels/719497620560543766/1078162827983990835/1078201526096498768) on the Discord forum).

Does this mean NKRO needs a fix similar to HKRO's #1521 ?

**Comment by yemartin** [comment]
Pinging @jhorology and @petejohanson (from #1521) for visibility. Do you have any idea about this?

**Comment by petejohanson** [comment]
> With a Kinesis Advantage360 Pro, even with the fix introduced by #1521, `LANG1` and `LANG2` did not work out of the box on macOS. `Key Codes.app` would not show any output when pressing these keys.
> 
> The Kinesis firmware builder tool has [NKRO enabled by default](https://github.com/KinesisCorporation/Adv360-Pro-ZMK/blob/09ff934f7d2a42e3b0b8e3f65595732536baf72d/config/boards/arm/adv360/adv360_left_defconfig#L53). But I had to [turn NKRO off](https://github.com/yemartin/Adv360-Pro-ZMK/commit/05840e690a687ea27ff743488837c48d50b59978) to get `LANG1` and `LANG2` to work (thanks to @caksoylar invaluable help and [spot-on suggestion](https://discord.com/channels/719497620560543766/1078162827983990835/1078201526096498768) on the Discord forum).
> 
> Does this mean NKRO needs a fix similar to HKRO's #1521 ?

The reason this does not work is because we limit our NKRO to only generate entries in the "bitfield" for HID up to `HID_USAGE_KEY_KEYPAD_EQUAL` which is `0x67`.  See https://usb.org/sites/default/files/hut1_4.pdf#chapter.10 where these are spec'd. Sadly, that means any of the keypad usages *after* that entry will not work.

See https://github.com/zmkfirmware/zmk/blob/main/app/include/zmk/hid.h#L16 for the spot in the code where this occurs. The *rest* of the HID code should, *in theory* work with a higher limit, at the expense of a larger payload size for the HID GATT reports. If you tried manually bumping this define to a later usage, and it works, I'd suggest moving the actual upper bound to a Kconfig setting that defaults to the current value but could be overridden.

**Comment by jdack41** [comment]
Thank you @jhorology for fixing this issue.

@petejohanson 
> I recommend you to delete all wireless pairing at first.
This process needed for my environment, and it worked after re-pairing.
