### ISSUE TITLE
Missing documentation on the user of `ZMK_CONFIG` define for user keymaps, etc.

### ISSUE THREAD

**Issue by petejohanson** [zmkfirmware/zmk#138]
We only have "implicit" documentation on the use of the `ZMK_CONFIG` variable and corresponding directory.

Docs should include:

* Describe the motivation behind the config directories.
  * Keep in-tree keymaps as "stock", and allow users to customize without adding to the core repo.
  * Allow users to version their custom handwires or niche boards out of tree, without forking ZMK and requiring constant merging of upstream ZMK.
* What it is, and what it can contain.
  * Toplevel shield/board config and keymap overrides.
  * `boards/` directory structure for out of tree boards and shields.
* How to build locally using `ZMK_CONFIG`.

**Comment by petejohanson** [comment]
@kurtis-lew is working on this for us. Thanks!

**Comment by kurtis-lew** [comment]
@petejohanson
I don't remember who it was, I believe it was @chenkevinh, but I think that [this page]( https://zmkfirmware.dev/docs/customization) in the docs serves as a good starting point for further documentation for this issue. I'd think it would be appropriate to add the extra details (motivation behind config directories, what they are/what they contain, how to build locally) here instead of adding an entirely new page. What do you say?

**Comment by caksoylar** [comment]
Looks like this was already addressed, closing.
