### ISSUE TITLE
Battery drain on peripheral side of split KB using nice!nano v2

### ISSUE THREAD

**Issue by abonham** [zmkfirmware/zmk#1417]
Thanks for all the hard work on an amazing firmware!

I'm using a Ferris Sweep with a pair of nice!nano v2's and I'm seeing extreme battery drain on the peripheral side when using BLE. I've tested on macOS 12 and Win10, no difference there.

I'm using 120mAh 3.7V 501225 batteries from (here)[https://core-electronics.com.au/lipo-polymer-lithium-ion-battery-120mah.html]. The right side only gets about 2 hours of battery, but even the left side only gets about 3 days. The power profile estimates I should get 2 weeks on the central and 3 months on the peripheral side.

I've been through any post I can find about battery issues and tried everything I've found but nothing seems to help. I've also replaced the battery multiple times, tested the batteries with a multimeter and swapped them between sides with no difference.

cradio.conf:
```
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=600000
CONFIG_ZMK_IDLE_TIMEOUT=120000
```

build.yaml
```
---
include:
  - board: nice_nano_v2
    shield: cradio_left
  - board: nice_nano_v2
    shield: cradio_right
```

and my full config is here: [](https://github.com/abonham/zmk-config) for reference.

Any help would be greatly appreciated!

**Comment by caksoylar** [comment]
Just one theory, but the very high battery use on the peripheral side might be due to a short between RAW/GND pins like a flux bridge, which would continuously leak some current. For the central side it might just be due to the high idle timeout; the default value is 10 seconds and you are setting it to two minutes.

Also a heads up: You might get better and more timely help in the ZMK Discord since debugging these issues with real-time conversations is easier, and potentially has a larger audience that can help: https://zmk.dev/community/discord/invite

**Comment by abonham** [comment]
Thank you so much for very usable feedback! Will go over it with a microscope and see what I can see!

**Comment by abonham** [comment]
Update: it was indeed a bad nice!nano, still waiting to hear back on getting a warranty replacement, but I purchased a new one in the mean time. Issue has been resolved so far; after a full day of use, battery has only dropped 2% rather than 300%.

**Comment by n0x00x** [comment]
> Update: it was indeed a bad nice!nano, still waiting to hear back on getting a warranty replacement, but I purchased a new one in the mean time. Issue has been resolved so far; after a full day of use, battery has only dropped 2% rather than 300%.

How did you determine that nano was bad? i think im having the same issue :(

**Comment by stiliajohny** [comment]
Following 

Same issue
