### ISSUE TITLE
Hyper key (`Ctrl`, `Shift`, `Alt`, `Cmd`) not working

### ISSUE THREAD

**Issue by skamelone** [zmkfirmware/zmk#1463]
I'm trying to use the following mapping for the "Hyper" key (`Ctrl`, `Shift`, `Alt`, `Cmd`), but it doesn't compile.
```
&mt LC(LS(LALT(LGUI))) END
```

It compiles if I remove `Cmd` (becoming the "Meh" key mapping) as follows

```
&mt LC(LS(LALT)) END
```

 Any idea what I'm doing wrong?

**Comment by caksoylar** [comment]
Hi, you have a mistake in your syntax. You should be using `LA` instead of `LALT` when using it as a [modifier function](https://zmk.dev/docs/codes/modifiers#modifier-functions) rather than a plain keycode.

In general for user questions I'd encourage you to ask at the [ZMK Discord](https://zmk.dev/community/discord/invite) where you can get faster help and a larger audience.
