### ISSUE TITLE
Unable to get 2 characters to output when pressing same characters on split keyboard

### ISSUE THREAD

**Issue by dlip** [zmkfirmware/zmk#1866]
For example on a split keyboard that has 'a' on the left and right sides and you press them at the same time, it only outputs a single 'a' instead of 'aa'. Is this a debounce issue or something else?

**Comment by caksoylar** [comment]
This is the current expected behavior, doing that will send two key press events without releasing the first one, and OS ignores the extra press event since there was no release. See #1828 for an enhancement to automatically send releases as well. If you test it, a comment on the PR would be appreciated.

**Comment by dlip** [comment]
closing as dup of #1828
