### ISSUE TITLE
CMake version incorrect in ZMK documentation.

### ISSUE THREAD

**Issue by BrainWart** [zmkfirmware/zmk#402]
ZMK uses the CMake command 'PREPEND` which is not found until version 3.15. ZMK documentation matches Zephyr's documentation of suggesting version 3.13.1 or above at this time and that is not correct.

**Comment by innovaker** [comment]
Thanks @BrainWart.  Good spot, this looks like what I encountered early on when I didn't understand it.

I believe this is due to a ZMK addition which makes use of `PREPEND`:
```
list(PREPEND KEYMAP_DIRS "${ZMK_CONFIG}")
```
`/home/innovaker/zmk/app/cmake/zmk_config.cmake` line 88

If my current modular prototyping pays off then it should make the above obsolete, at which point we can revert this fix to realign with Zephyr.
