### ISSUE TITLE
Github authentication method deprecation

### ISSUE THREAD

**Issue by keyboard-magpie** [zmkfirmware/zmk#560]
<img width="921" alt="Screenshot 2020-12-31 at 14 45 22" src="https://user-images.githubusercontent.com/19674258/103414824-699cb080-4b77-11eb-913b-8b3a043ad3e7.png">

When using the basic setup scripts (https://zmkfirmware.dev/docs/user-setup - curl and wget methods)
it appears we will soon run into the above issue meaning the only way to authorise will be via tokens- 

I propose the docs need amending to reflect this

**Comment by joelspadin** [comment]
We should probably have the docs point to https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/creating-a-personal-access-token (and optionally https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/connecting-to-github-with-ssh since SSH keys should still work too).

**Comment by caksoylar** [comment]
Docs no longer go into detail of setting up git access and point to Github docs, so this no longer seems applicable.
